services:
  master_db:
    build:
      context: ./master_slave_replication/master
      dockerfile: Dockerfile
    container_name: master_db
    hostname: master_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./master_slave_replication/master/data:/var/lib/postgresql/data
    # command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  slave_db_one:
    build:
      context: ./master_slave_replication/slave
      dockerfile: Dockerfile.slave_db_one
    container_name: slave_db_one
    hostname: slave_db_one
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REPLICATOR_USER: ${REPLICATOR_USER}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD}
      MASTER_HOST: master_db
    depends_on:
      master_db:
        condition: service_healthy
    volumes:
      - ./master_slave_replication/slave/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  
  slave_db_two:
    build:
      context: ./master_slave_replication/slave
      dockerfile: Dockerfile.slave_db_two
    container_name: slave_db_two
    hostname: slave_db_two
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REPLICATOR_USER: ${REPLICATOR_USER}
      REPLICATOR_PASSWORD: ${REPLICATOR_PASSWORD}
      MASTER_HOST: master_db
    depends_on:
      master_db:
        condition: service_healthy
    volumes:
      - ./master_slave_replication/slave/data_two:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  
  # pgpool:
  #   build:
  #     context: ./pgpool
  #     dockerfile: Dockerfile
  #   container_name: pgpool
  #   hostname: pgpool
  #   environment:
  #     PGPOOL_USER: "postgres"       
  #     PGPOOL_PASSWORD: "postgres"
  #   volumes:
  #     - ./pgpool/pgpool.conf:/etc/pgpool2/pgpool.conf
  #     - ./pgpool/pool_hba.conf:/etc/pgpool2/pool_hba.conf
  #     - ./pgpool/pcp.conf:/etc/pgpool2/pcp.conf
  #   depends_on:
  #     master_db:
  #       condition: service_healthy
  #     slave_db_one:
  #       condition: service_healthy
  #     slave_db_two:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-h", "localhost", "-p", "9999"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10


  pgpool:
    build:
      context: ./pgpool
      dockerfile: Dockerfile
    container_name: pgpool
    hostname: pgpool
    environment:
      - PGPOOL_USER=${DB_TEST_USER}
      - PGPOOL_PASSWORD=${DB_TEST_PASSWORD}
      - PGPOOL_HEALTH_CHECK_USER=${PGPOOL_HEALTHCHECK_USER}
      - PGPOOL_HEALTH_CHECK_PASSWORD=${PGPOOL_HEALTHCHECK_PASSWORD}
    ports:
      - "9999:9999"
      - "9898:9898"
    volumes:
      # - ./pgpool/config:/usr/local/pgpool-II/etc:ro
      - ./pgpool/config:/usr/local/pgpool-II/etc
      - ./pgpool/runtime:/var/run/pgpool
    depends_on:
      master_db:
        condition: service_healthy
      slave_db_one:
        condition: service_healthy
      slave_db_two:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "pgpool_healthcheck", "-p", "9999"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  
  api_migrator:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api-image
    container_name: api_migrator
    hostname: api_migrator
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MASTER_DB_HOST: pgpool
      MASTER_DB_PORT: 9999
    entrypoint: /app/entrypoint.sh
    depends_on:
      pgpool:
        condition: service_healthy
    volumes:
      - ./api:/app
    restart: "no"


  api_replica_1:
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    image: api-image
    container_name: api_replica_1
    hostname: api_replica_1
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MASTER_DB_HOST: pgpool
      MASTER_DB_PORT: 9999
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    # entrypoint: /app/entrypoint.sh
    command: daphne -b 0.0.0.0 -p 8000 main.asgi:application  # this is for tcp
    depends_on:
      redis:
        condition: service_healthy
      pgpool:
        condition: service_healthy
      api_migrator:
        condition: service_completed_successfully
      
    volumes:
      - ./api:/app
      # - ./socket:/app/socket  # this is for unix
  

  api_replica_2:
    image: api-image
    container_name: api_replica_2
    hostname: api_replica_2
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MASTER_DB_HOST: pgpool
      MASTER_DB_PORT: 9999
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    # entrypoint: /app/entrypoint.sh
    command: daphne -b 0.0.0.0 -p 8000 main.asgi:application # this is for tcp
    depends_on:
      redis:
        condition: service_healthy
      pgpool:
        condition: service_healthy
      api_migrator:
        condition: service_completed_successfully
      
    volumes:
      - ./api:/app
      # - ./socket:/app/socket # this is for unix
  

  celery:
    image: api-image
    container_name: celery
    hostname: celery
    command: celery -A main worker --loglevel=info
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MASTER_DB_HOST: pgpool
      MASTER_DB_PORT: 9999
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./api:/app

    depends_on:
      redis:
        condition: service_healthy
      pgpool:
        condition: service_healthy
      api_migrator:
        condition: service_completed_successfully

  

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    ports:
      - "5000:80"
    depends_on:
      - api_replica_1
      - api_replica_2
    # volumes:
    #   - ./socket:/app/socket # this is for unix



# volumes:
#   pgpool-runtime:
